apiVersion: v1
kind: Secret
metadata:
  name: door-sensor-secrets
type: Opaque
stringData:
  # CHANGE THESE VALUES
  TUYA_ACCESS_ID: "your_access_id"
  TUYA_ACCESS_SECRET: "your_access_secret"
  TUYA_ENDPOINT: "https://openapi-sg.iotbing.com"
  TUYA_PULSAR_ENDPOINT: "wss://mqe-sg.iotbing.com:8285/"
  DEVICE_ID: "your_device_id"
  WA_API_URL: "http://whatsapp-service:3000"
  WA_API_USER: "user"
  WA_API_PASSWORD: "password"
  WA_GROUP_ID: "123456789@g.us"
