apiVersion: v1
kind: Service
metadata:
  name: door-sensor-service
  labels:
    app: door-sensor-monitor
spec:
  type: ClusterIP
  selector:
    app: door-sensor-monitor
  ports:
    - port: 5001
      targetPort: 5001
      protocol: TCP
      name: http
